spring:
  profiles:
    active: local
  datasource:
    url: jdbc:h2:tcp://localhost/~/wwwalk
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        #     show_sql: true
        format_sql: true
  data:
    web:
      pageable:
        default-page-size: 10
        max-page-size: 2000

jwt:
  header: Authorization
  secret: U3ByaW5nLUJvb3QtQmFja2VuZC1Qcm9qZWN0LVJlZmFjdG9yaW5nLUFuZC1TdHVkeS1Gcm9tLUFuYWNvbmRhCg==
  token-validity-in-seconds: 86400
#trace < debug < info < warn < error
logging.level:
#  root: info
  org.hibernate.SQL: debug
#  org.hibernate.type: trace